FROM microsoft/dotnet:2.2-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 80

FROM microsoft/dotnet:2.2-sdk AS build
WORKDIR /src
COPY ["src/", "."]
RUN dotnet restore "Queue.Consumer.Mongo/Queue.Consumer.Mongo.csproj"
WORKDIR "/src/Queue.Consumer.Mongo/"
RUN dotnet build "Queue.Consumer.Mongo.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "Queue.Consumer.Mongo.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "Queue.Consumer.Mongo.dll"]